config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"

  resources :users do
    resources :products
  end

  resources :products do
    resources :reviews, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", small: "140x140>", thumb: "64x64!" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :reviews
  has_many :users, :through => :reviews
  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates :author, :presence => true
  validates :content, :presence => true
  validates :rating, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end



private
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:notice] = "Your review was saved!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Oops!"
      redirect_to new_product_review_path(@product)
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Your changes have been saved!"
      redirect_to product_path(params[:product_id])
    else
      flash[:alert] = "Oops!"
      redirect_to edit_product_review_path(params[:product_id], params[:id])
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content, :rating, product_id: @product.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <%= image_tag("main.png", class: "responsive-img center") %>
</div>

<div class="center">
  <h4 class="featured">Featured Collections</h4>
  <hr>
</div>

<div class="row home">
  <% if @products.any? %>
    <% @products.each do |product| %>
      <div class="col s12 m4">
        <div class="card small z-depth-0">
          <div class="card-image">
            <%= link_to image_tag(product.image, class: "responsive-img"), product_path(product) %><br>
          </div>
          <div class="card-content center">
            <%= link_to product.name, product_path(product) %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
      <p>There are no products yet!</p>
  <% end %>
</div>

<div class="center">
  <h4 class="featured">Welcome!</h4>
  <hr>
  <h6>We're Freeformind, and we're glad you're here. We design charms and ornaments inspired by places and objects people love. We create our products using small-batch manufacturing techniques such as 3D printing, lost wax casting, and photo-etching. We seek to propel interest in science, technology, engineering, and math. We geek out on architecture and 3D printing, and it inspires us to create intricate shapes that can't be manufactured through traditional casting processes. Our products can be found online, in museum stores, and boutique gift shops throughout the US. Freeformind was established in 2014 in Emeryville, Ca.</h6>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeformind</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="/" class="left brand-logo">Free <span class="for-logo">for</span> Mind</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Products', products_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% if current_user.admin %>
              <li><%= link_to "Admin", rails_admin_path %></li>
            <% end %>
              <li><%= current_user.email %></li>
            <% else %>
              <li><%= link_to "Sign-up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul><br>
       </div>
      </nav>
    </div>

    <div class="container">
      <div class="notice">
        <%= flash[:notice] %>
      </div>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="center">
  <h4 class="featured">Featured Collections</h4>
  <hr>
</div>

<div class="row home">
  <% if @products.any? %>
    <% @products.each do |product| %>
      <div class="col s12 m4">
        <div class="card small z-depth-0">
          <div class="card-image">
            <%= link_to image_tag(product.image, class: "responsive-img"), product_path(product) %><br>
          </div>
          <div class="card-content center">
            <%= link_to product.name, product_path(product) %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
      <p>There are no products yet!</p>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col s6">
    <%= image_tag(@product.image.url(:large), class: "responsive-img product-show") %>
  </div>
  <div class="col s6">
    <h4 class="center"><%= @product.name %></h4>
    <p class="center">$<%= @product.price %></p>
    <p><%= @product.description %></p>
  </div>
</div>

<hr>

<div class="row">
  <div class="col s12 center">
    <% if @reviews.any? %>
      <% @reviews.each do |review| %>
      <div class="row">
        <div class="col s12">
          <div class="card horizontal">
            <div class="card-stacked">
              <div class="card-content">
                <h5>Reviewed by <%= review.author %></h5>
                <p class="red-text"><%= review.rating %> stars</p>
                <p><%= review.content %></p>
              </div>
              <div class="card-action">
                <% if review.user_id == current_user.id %>
                  <%= link_to "Edit Review", edit_product_review_path(@product, review.id) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% else %>
      <p>Be the first to review this product!</p>
    <% end %>
    <%= link_to "New Review", new_product_review_path(@product), class: "new-review" %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.submit "Save", class: "btn" %>
<% end %>

app/views/reviews/edit.html.erb
<h1 class="center">Edit Review</h1>

<%= render "layouts/errors", :object => @review %>

<%= render "form" %>

app/views/reviews/new.html.erb
<h1 class="center">New Review</h1>

<%= render "layouts/errors", :object => @review %>

<%= render "form" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>